# Generated by Django 4.2.24 on 2025-09-06 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_carouselbanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, help_text='Emoji or short text icon for frontend display', max_length=10, null=True),
        ),
    ]
