# Generated by Django 4.2.24 on 2025-09-06 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='sold_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sold price per unit'),
        ),
    ]
