# Generated by Django 4.2.24 on 2025-09-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_sale_sold_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Ecolo-Sur Market 🌱', max_length=255)),
                ('whatsapp_number', models.CharField(help_text='Include country code, e.g., 50585723217', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Business Setting',
                'verbose_name_plural': 'Business Settings',
            },
        ),
    ]
