# Generated by Django 4.2.24 on 2025-09-11 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_businesssettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselbanner',
            name='image',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.URLField(blank=True),
        ),
    ]
