# Generated by Django 4.2.24 on 2025-09-21 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_carouselbanner_image_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='sku',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
    ]
